#!/bin/bash

ROOTDIR=$(git rev-parse --show-toplevel 2>/dev/null)

git clone https://github.com/derlin/hepqpr-qallse
cp -r hepqpr-qallse/src/hepqpr $ROOTDIR/source
ln -s $ROOTDIR/source/hepqpr $ROOTDIR/source/ja/hepqpr
