FROM yiiyama/jupyterbook-qiskit-packages:1.1.3 AS packages_cleaned

COPY clean_packages.sh /
RUN /clean_packages.sh


FROM ubuntu:latest

RUN apt-get -y update && \
    apt-get install -y python3 && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=packages_cleaned /packages.tar.gz /

RUN tar -C / -xzf /packages.tar.gz && rm /packages.tar.gz
