FROM ubuntu:latest

RUN apt-get -y update && \
    apt-get install -y \
       python3 \
       python3-venv \
       python3-pip && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir myst-parser==0.13.3 && \
    pip3 install --no-cache-dir qiskit jupyterlab matplotlib pylatexenc jupyter-book

RUN mkdir -p /tmp/qc-workbook
